version: "3.9"

services:
  nginx:
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    ports:
      - "443:443"
    networks:
      - wp-network
    volumes:
      - wp-data:/var/www/html

  wordpress:
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    expose:
      - "9000"
    networks:
      - wp-network
    volumes:
      - wp-data:/var/www/html

networks:
  wp-network:
    driver: bridge

volumes:
  wp-data: