version: "3.9"

services:

  mariadb:
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    env_file:
      - .env
    expose:
      - "3306"
    environment:
      - MYSQL_ROOT_PASSWORD=senha1
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=phiolive
      - MYSQL_PASSWORD=senha1
    volumes:
      - db_data:/var/lib/mysql

  wordpress:
    depends_on:
      - mariadb
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    expose:
      - "9000"
    networks:
      - wp-network
    volumes:
      - wp_data:/var/www/html

  nginx:
    depends_on:
      - wordpress
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    ports:
      - "443:443"
    networks:
      - wp-network
    volumes:
      - wp_data:/var/www/html





networks:
  wp-network:
    driver: bridge

volumes:
  wp_data:
  db_data: